### ISSUE TITLE
Reconsider your employment status :)

### ISSUE THREAD

**Issue by jjudge** [saneshark/saneshark.github.io#7]
Hey Kam,

I'm building a new product called [Bright](https://www.bright.io) and looking for an [engineer](https://angel.co/bright-io/jobs/141493-software-engineer) to join me in Chicago. I found you on Angellist and noticed you took a FT gig in f263b47348cf14a5ee5736ff9883290b46253105. If anything changes, I'd love to talk!

Thanks,
Jeff

**Comment by saneshark** [comment]
Hi Jeff,

Clever guy checking my within. :) I did take a job and I'm excited about it
but let's see how it goes. Feel free to connect on AngelList or LinkedIn.

Kam

**Comment by jjudge** [comment]
OK, I'll close out the issue...for now :)

Good luck with your new gig!
